# Generated by Django 4.1.7 on 2023-11-14 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRM_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coment',
            new_name='Comment',
        ),
    ]
