# Generated by Django 4.1.7 on 2023-10-23 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigation_project',
            name='objetivos',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
