# Generated by Django 4.2.5 on 2023-09-24 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRM_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allie_Type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Allie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('image_link', models.CharField(max_length=200)),
                ('allie_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRM_app.allie_type')),
            ],
        ),
    ]
