# Generated by Django 4.2.5 on 2023-09-16 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
