# Generated by Django 4.2.5 on 2023-11-06 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRM_app', '0002_investigation_project_objetivos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='naame',
            new_name='name',
        ),
    ]
