# Generated by Django 4.2.5 on 2023-09-25 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRM_app', '0003_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
