# Generated by Django 4.2.5 on 2023-11-06 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRM_app', '0006_user_type_user_user_type_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='CRM_app.user_type'),
        ),
    ]
