# Generated by Django 4.2.5 on 2023-09-26 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRM_app', '0007_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=20)),
                ('aux_email', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=20)),
                ('allie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRM_app.allie')),
            ],
        ),
    ]
