# Generated by Django 4.2.5 on 2023-09-27 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRM_app', '0008_contactinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation_Type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('max_value', models.IntegerField()),
                ('min_value', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Event_Type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Investigation_Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('active', models.TextField(max_length=1)),
                ('start_date', models.DateField()),
                ('finish_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('doi', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('investigation_project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRM_app.investigation_project')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=20)),
                ('objective', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('event_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRM_app.event_type')),
            ],
        ),
        migrations.CreateModel(
            name='EventAllie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRM_app.allie')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRM_app.event')),
            ],
            options={
                'db_table': 'EVENT_ALLIE',
                'unique_together': {('event', 'allie')},
            },
        ),
        migrations.CreateModel(
            name='AllieProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRM_app.allie')),
                ('investigation_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRM_app.investigation_project')),
            ],
            options={
                'db_table': 'ALLIE_PROJECT',
                'unique_together': {('allie', 'investigation_project')},
            },
        ),
    ]
