# Generated by Django 4.2.5 on 2023-09-27 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRM_app', '0009_donation_type_event_type_investigation_project_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting_type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='allie',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='Practicing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=20)),
                ('allie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRM_app.allie')),
                ('career_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRM_app.career')),
                ('gender_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRM_app.gender')),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200, null=True)),
                ('objective', models.CharField(max_length=200, null=True)),
                ('allie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRM_app.allie')),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('amount', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=20, null=True)),
                ('allie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRM_app.allie')),
                ('donation_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRM_app.donation_type')),
            ],
        ),
    ]
