# Generated by Django 4.2.5 on 2023-10-01 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM_app', '0011_alter_practicing_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicing',
            name='image_link',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
