# Generated by Django 4.2.5 on 2023-10-04 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRM_app', '0012_practicing_image_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='name',
        ),
    ]
