# Generated by Django 4.2.5 on 2023-10-11 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM_app', '0013_remove_donation_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='investigation_project',
            name='finish_date',
            field=models.DateField(null=True),
        ),
    ]
