# Generated by Django 4.2.5 on 2023-10-15 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRM_app', '0014_publication_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='meeting_type_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='CRM_app.meeting_type'),
            preserve_default=False,
        ),
    ]
