# Generated by Django 4.2.6 on 2023-10-16 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM_app', '0016_event_image_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image_link',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
